---

builds:
  docker_image_name: FreeLunchCI/example-web-app:green

services:
  db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"
web:
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  ports:
    - "3000:3000"
links:
  - db
volumes:
  - .:/myapp

outputs:

  - type: ecr
    image: FreeLunchCI/example-web-app:green
    registry: 703587889398.dkr.ecr.us-east-1.amazonaws.com
    repository: example-web-app:green

  - type: kube
    #user: flci::kube_user
    #token: flci::kube_token
    #client_certificate: flci::kube_client_certificate
    #server: flci::kube_server
    kube_config_path: ~/.kube/config
    kube_selector: app=example-web-app
    kube_rc_path: k8s/example-web-app-rc.yml
    kube_dir: k8s
