apiVersion: v1
kind: ReplicationController
metadata:
  name: example-web-app-green
  labels:
    app: example-web-app
spec:
  replicas: 1
  selector:
    app: example-web-app
    version: v0.1.14
  template:
    metadata:
      labels:
        app: example-web-app
        version: v0.1.14
    spec:
      containers:
      - name: example-web-app
        imagePullPolicy: Always
        image: 703587889398.dkr.ecr.us-east-1.amazonaws.com/example-web-app:green
        ports:
        - name: appport
          containerPort: 5000
        volumeMounts:
         - name: docker-sock
           mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
