apiVersion: v1
kind: Service
metadata:
  name: example-web-app-elb
  labels:
    app: example-web-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: example-web-app
